// SPDX-FileCopyrightText: 2024 Cesanta Software Limited
// SPDX-License-Identifier: GPL-2.0-only or commercial
// Generated by Mongoose Wizard, https://mongoose.ws/wizard/

// Default mock implementation of the API callbacks

#include "mongoose_glue.h"
struct modbInverter s_modbInverter = {10, 1, 10, 1, 2, 61530, 0, 10, 1, 1, 61518, 0, 10, 1, 1, 61517, 0, 10, 1, 2, 61528, 0, 10, 1, 1, 61526, 0, 10, 1, 1, 61527, 0, 10, 1, 2, 61522, 0, 10, 1, 2, 61520, 0, 10, 1, 1, 61518, 0, 10, 1, 1, 61517, 0};
void glue_get_modbInverter(struct modbInverter *data) {
  *data = s_modbInverter;  // Sync with your device
}
void glue_set_modbInverter(struct modbInverter *data) {
  s_modbInverter = *data; // Sync with your device
}

struct modbSensors s_modbSensors = {15, 42, 1.5, 1, 0, 0, -1, 20, 1, 1, 0, 0, -1, 19, 1, 1, 0, 0, -1, 17, 1, 1, 6, 8192, 0, 16, 1, 1, 2, 8192, 0, 16};
void glue_get_modbSensors(struct modbSensors *data) {
  *data = s_modbSensors;  // Sync with your device
}
void glue_set_modbSensors(struct modbSensors *data) {
  s_modbSensors = *data; // Sync with your device
}

struct modbBattery s_modbBattery = {30, 3, 10, 1, 1, 276, 0, 1, 1, 1, 268, 0, 1, 1, 1, 260, 0, 1, 1, 1, 256, 0};
void glue_get_modbBattery(struct modbBattery *data) {
  *data = s_modbBattery;  // Sync with your device
}
void glue_set_modbBattery(struct modbBattery *data) {
  s_modbBattery = *data; // Sync with your device
}

struct modbPanels s_modbPanels = {30, 4, 10, 1, 1, 272, 0, 10, 1, 1, 271, 0, 10, 1, 1, 264, 0, 10, 1, 1, 263, 0, 1, 1, 1, 267, 0};
void glue_get_modbPanels(struct modbPanels *data) {
  *data = s_modbPanels;  // Sync with your device
}
void glue_set_modbPanels(struct modbPanels *data) {
  s_modbPanels = *data; // Sync with your device
}

uint64_t s_action_timeout_reboot;  // Time when reboot ends
bool glue_check_reboot(void) {
  return s_action_timeout_reboot > mg_now(); // Return true if reboot is in progress
}
void glue_start_reboot(struct mg_str params) {
  MG_DEBUG(("Passed parameters: [%.*s]", params.len, params.buf));
  s_action_timeout_reboot = mg_now() + 1000; // Start reboot, finish after 1 second
}

struct limits s_limits = {90, 50, 32, 19, 31, 19, 70, 50, 70, 40, 42, 40, 42, 40, 42, 40, 42, 40, 42, 40, 42, 40, 820, 720, 850, 720, 820, 720, 820, 780, 50, 10, 5000, 0, 100, 20, 80, 20, 15, 14, 390, 340};
void glue_get_limits(struct limits *data) {
  *data = s_limits;  // Sync with your device
}
void glue_set_limits(struct limits *data) {
  s_limits = *data; // Sync with your device
}

struct profile s_profile = {""};
void glue_get_profile(struct profile *data) {
  *data = s_profile;  // Sync with your device
}
void glue_set_profile(struct profile *data) {
  s_profile = *data; // Sync with your device
}

struct settings s_settings = {false, false, false, 0, 0, 0, "", "", false, 0, ""};
void glue_get_settings(struct settings *data) {
  *data = s_settings;  // Sync with your device
}
void glue_set_settings(struct settings *data) {
  s_settings = *data; // Sync with your device
}

struct system s_system = {0, 1000, false, "5.0.1", false, 3, 5, 25, 0, 0, "", "", "csttpstt", "robert", "http://64.123.180.233:1883", "", 60000, "", "", 0, false, 400000, 10000};
void glue_get_system(struct system *data) {
  *data = s_system;  // Sync with your device
}
void glue_set_system(struct system *data) {
  s_system = *data; // Sync with your device
}

struct sysset s_sysset = {"", "", 0, 0, false, false, 0, 0, "", "", "", 0, 0, 0, 0, 0, 0, ""};
void glue_get_sysset(struct sysset *data) {
  *data = s_sysset;  // Sync with your device
}
void glue_set_sysset(struct sysset *data) {
  s_sysset = *data; // Sync with your device
}
