// SPDX-FileCopyrightText: 2024 Cesanta Software Limited
// SPDX-License-Identifier: GPL-2.0-only or commercial
// Generated by Mongoose Wizard, https://mongoose.ws/wizard/

#ifndef MONGOOSE_GLUE_H
#define MONGOOSE_GLUE_H

#ifdef __cplusplus
extern "C" {
#endif

#include "mongoose.h"

#define WIZARD_ENABLE_HTTP 1
#define WIZARD_ENABLE_HTTPS 0
#define WIZARD_ENABLE_HTTP_UI 1
#define WIZARD_ENABLE_HTTP_UI_LOGIN 0

#define WIZARD_ENABLE_WEBSOCKET 0

#define WIZARD_ENABLE_MQTT 0
#define WIZARD_MQTT_URL ""

#define WIZARD_ENABLE_SNTP 0  // Enable time sync.
#define WIZARD_SNTP_TYPE 0    // 0: default Google, 1: DHCP, 2: custom
#define WIZARD_SNTP_URL "udp://time.google.com:123"  // Custom SNTP server URL
#define WIZARD_SNTP_INTERVAL_SECONDS 3600            // Frequency of SNTP syncs

#define WIZARD_DNS_TYPE 0  // 0: default Google, 1: DHCP, 2: custom
#define WIZARD_DNS_URL "udp://8.8.8.8:53"  // Custom DNS server URL
#define WIZARD_CAPTIVE_PORTAL 0
#define WIZARD_ENABLE_MDNS 0
#define WIZARD_MDNS_NAME "mongoose"

#define WIZARD_ENABLE_WIFI 0
#define WIZARD_WIFI_NAME "MyNet"
#define WIZARD_WIFI_PASS "MyPass"
#define WIZARD_ENABLE_WIFI_AP 0
#define WIZARD_WIFI_AP_NAME "MyAp"
#define WIZARD_WIFI_AP_PASS "MyApPass"

#define WIZARD_ENABLE_MODBUS 0
#define WIZARD_MODBUS_PORT 502

#ifndef WIZARD_REBOOT_TIMEOUT_MS
#define WIZARD_REBOOT_TIMEOUT_MS 500
#endif

void mongoose_init(void);    // Initialise Mongoose
void mongoose_poll(void);    // Poll Mongoose
extern struct mg_mgr g_mgr;  // Mongoose event manager

void mongoose_set_http_handlers(const char *name, ...);
void mongoose_add_ws_handler(unsigned ms, void (*)(struct mg_connection *));
void mongoose_add_ws_reporter(unsigned ms, const char *name);

struct mongoose_mqtt_handlers {
  struct mg_connection *(*connect_fn)(mg_event_handler_t);
  void (*on_connect_fn)(struct mg_connection *, int);
  void (*on_message_fn)(struct mg_connection *, struct mg_str, struct mg_str);
  void (*on_cmd_fn)(struct mg_connection *, struct mg_mqtt_message *);
};
void mongoose_set_mqtt_handlers(struct mongoose_mqtt_handlers *);

struct mongoose_modbus_handlers {
  bool (*read_reg_fn)(uint16_t address, uint16_t *value);
  bool (*write_reg_fn)(uint16_t address, uint16_t value);
};
void mongoose_set_modbus_handlers(struct mongoose_modbus_handlers *);

void mongoose_set_sntp_handler(void (*fn)(uint64_t epoch_ms));
void mongoose_set_sntp_server(const char *url);

void mongoose_set_auth_handler(int (*fn)(const char *user, const char *pass));

void mongoose_add_custom_handler(const char *url_pattern, mg_event_handler_t);

#if WIZARD_ENABLE_MQTT
void glue_lock_init(void);  // Initialise global Mongoose mutex
void glue_lock(void);       // Lock global Mongoose mutex
void glue_unlock(void);     // Unlock global Mongoose mutex
#else
#define glue_lock_init()
#define glue_lock()
#define glue_unlock()
#endif

// Update MDNS name. Works when MDNS is enabled.
void glue_mdns_update_name(const char *newname);

// Increment device change state counter - trigger UI refresh
void glue_update_state(void);

// Firmware Glue

struct modbInverter {
  int refresh_rate;
  int InverterAddress;
  float I11_BatTempMux;
  int I11_BatTempPoints;
  int I11_BatTempStart;
  int I11_BatTempOff;
  float I10_LoadUsedHoyMux;
  int I10_LoadUsedHoyPoints;
  int I10_LoadUsedHoyStart;
  int I10_LoadUsedHoyOff;
  float I9_BatDscHoyMux;
  int I9_BatDscHoyPoints;
  int I9_BatDscHoyStart;
  int I9_BatDscHoyOff;
  float I8_BatChdHoyMux;
  int I8_BatChdHoyPoints;
  int I8_BatChdHoyStart;
  int I8_BatChdHoyOff;
  float I7_LoadUsedTotalMux;
  int I7_LoadUsedTotalPoints;
  int I7_LoadUsedTotalStart;  //  
  int I7_LoadUsedTotalOff;
  float I6_UsedkwhHoyMux;
  int I6_UsedkwhHoyPoints;
  int I6_UsedkwhHoyStart;
  int I6_UsedkwhHoyOff;
  float I5_GenkWhHoyMux;
  int I5_GenkWhHoyPoints;
  int I5_GenkWhHoyStart;
  int I5_GenkWhHoyOff;
  int I4_BatDscTotalMux;
  int I4_BatDscTotalPoints;
  int I4_BatDscTotalStart;
  int I4_BatDscTotalOff;
  int I3_BatChgTotalMux;
  int I3_BatChgTotalPoints;
  int I3_BatChgTotalStart;
  int I3_BatChgTotalOff;
  int I2_BatDscHoyMux;
  int I2_BatDscHoyPoints;
  int I2_BatDscHoyStart;
  int I2_BatDscHoyOff;
  int I1_BatChHoyMux;
  int I1_BatChHoyPoints;
  int I1_BatChHoyStart;
  int I1_BatChHoyOff;
};
void glue_get_modbInverter(struct modbInverter *);
void glue_set_modbInverter(struct modbInverter *);

struct modbSensors {
  int refresh_rate;
  float humMux;
  int humPoints;
  int humStart;
  int HumOffset;
  int HAddress;
  float AMux;
  int APoints;
  int AStart;
  int AOffset;
  int AAddress;
  float PHMux;
  int PHPoints;
  int PHStart;
  int PHOffset;
  int PHAddress;
  float DOMux;
  int DOPoints;
  int DOStart;
  int DOOffset;
  int DOAddress;
  float WMux;
  int WPoints;
  int WStart;
  int WOffset;
  int WAddress;
};
void glue_get_modbSensors(struct modbSensors *);
void glue_set_modbSensors(struct modbSensors *);

struct modbBattery {
  int refresh_rate;
  int batAddress;
  float tempMux;
  int tempPoints;
  int tempStart;
  int tempOffset;
  float cycleMux;
  int cyclePoints;
  int cycleStart;
  int cycleOffset;
  float SOHMux;
  int SOHPoints;
  int SOHStart;
  int SOHOffset;
  float SOCMux;
  int SOCPoints;
  int SOCStart;
  int SOCOffset;
};
void glue_get_modbBattery(struct modbBattery *);
void glue_set_modbBattery(struct modbBattery *);

struct modbPanels {
  int refresh_rate;
  int PVAddress;
  float PV2AmpsMux;
  int PV2AmpsPoints;
  int PV2AmpsStart;
  int PV2AmpsOffset;
  float PV2VMux;
  int PV2VPoints;
  int PV2VStart;
  int PV2VoltsOffset;
  float PV1AmpsMux;
  int PV1AmpsPoints;
  int PV1AmpsStart;
  int PV1_AmpsOffset;
  float PV1VMux;
  int PV1VPoints;
  int PV1VStart;
  int PV1VoltsOffset;
  float ChargeMux;
  int ChargePoints;
  int ChargeStart;
  int Charge_StateOffset;
};
void glue_get_modbPanels(struct modbPanels *);
void glue_set_modbPanels(struct modbPanels *);

void glue_start_reboot(struct mg_str);  // Start an action
bool glue_check_reboot(void);  // Check if action is still in progress

struct limits {
  int hummax;
  int hummin;
  int atempmax;
  int atempmin;
  int wtempmax;
  int wtempmin;
  int phmax;
  int phmin;
  int domax;
  int domin;
  int kwchoymax;
  int kwchoymin;
  int kwbatdhoymax;
  int kwbatdhoymin;
  int kwbatchoymax;
  int kwbatchoymin;
  int kwloadhoymax;
  int kwloadhoymin;
  int kwctodaymax;
  int kwctodaymin;
  int kwgtodaymax;
  int kwgtodaymin;
  int bdATotmax;
  int bdATotmin;
  int bcATotmax;
  int bcATotmin;
  int bdAhoymax;
  int bdAhoymin;
  int bcAhoymax;
  int bcAhoymin;
  int btempmax;
  int btempmin;
  int bcyclemax;
  int bcyclemin;
  int bSOHmax;
  int bSOHmin;
  int bSOCmax;
  int bSOCmin;
  int amax;
  int amin;
  int vmax;
  int vmin;
};
void glue_get_limits(struct limits *);
void glue_set_limits(struct limits *);

struct profile {
  char schedule[10000];
};
void glue_get_profile(struct profile *);
void glue_set_profile(struct profile *);

struct settings {
  bool delay_val;
  int nodes_val;
  int unit_val;
  int disable_val;
  char msg_val[60];
  char challenge_val[16];
  bool master_val;
  int pool_val;
  char mac_val[10];
};
void glue_get_settings(struct settings *);
void glue_set_settings(struct settings *);

struct system {
  int disable_val;
  int mqttreco_val;
  bool otf_val;
  char version_val[20];
  bool skipopt_val;
  int skip_val;
  int repeat_val;
  int baset_val;
  int maxamp_val;
  int minamp_val;
  char password_val[16];
  char loglevel_val[10];
  char mqttpass_val[30];
  char mqttuser_val[30];
  char mqttserver_val[60];
  char mqttcert_val[1900];
  int logtime_val;
  char ssidpass_val[16];
  char ssid_val[30];
  int meshid_val;
  bool security_val;
  int nodes_val;
  int conns_val;
};
void glue_get_system(struct system *);
void glue_set_system(struct system *);

struct sysset {
  char idf_val[100];
  char compile_val[100];
  int boot_val;
  int lreason_val;
  bool security_val;
  bool display_val;
  int lost_val;
  int writes_val;
  int reads_val;
  char nodetype_val[10];
  char mac_val[20];
  char mesh_val[20];
  int bytesin_val;
  int bytesout_val;
  int msgin_val;
  int msgout_val;
  int conns_val;
  int disco_val;
  char ldate_val[100];
};
void glue_get_sysset(struct sysset *);
void glue_set_sysset(struct sysset *);


#ifdef __cplusplus
}
#endif
#endif  // MONGOOSE_GLUE_H
