// SPDX-FileCopyrightText: 2024 Cesanta Software Limited
// SPDX-License-Identifier: GPL-2.0-only or commercial
// Generated by Mongoose Wizard, https://mongoose.ws/wizard/

#include "mongoose_glue.h"
#include "esp_spiffs.h"

#define WIFI_SSID "My_WiFi_Network"
#define WIFI_PASS "My_WiFi_Password"

extern void wifi_init(const char *ssid, const char *pass);

// API callback override example
// void my_get_leds(struct leds *leds) { leds->led1 = gpio_read(LED1); }
// void my_set_leds(struct leds *leds) { gpio_write(LED1, leds->led1); }

void app_main() {
  esp_vfs_spiffs_conf_t conf = {
    .base_path = "/spiffs",
    .max_files = 20,
    .format_if_mount_failed = true,
  };
  esp_vfs_spiffs_register(&conf);

  wifi_init(WIFI_SSID, WIFI_PASS); // This blocks until connected

  mongoose_init();
  // mongoose_set_http_handlers("leds", my_get_leds, my_set_leds);

  for (;;) {
    mongoose_poll();
  }
}
